debug: true
logging:
#    config: classpath:logback-spring.xml
    level:
        org:
            springframework:
                web: DEBUG
#mybatis:
#    config-locations: classpath:mybatis/mybatis-config.xml
#    mapper-locations: classpath:mybatis/mapper/*.xml
#    type-aliases-package: com.hk.ssm4.entity
server:
    port: 8866
    tomcat:
        uri-encoding: UTF-8
#spring:
#    datasource:
#        driverClassName: com.mysql.jdbc.Driver
#        password: root
#        url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
#        username: root
#    http:
#        encoding:
#            charset: UTF-8
#            enabled: true
#            force: true

# spring
spring:
  jta:
    atomikos:
      datasource:
        login-timeout: 30 
        max-pool-size: 25  
        min-pool-size: 3  
        max-lifetime: 20000  
        test-query: SELECT 1
        borrow-connection-timeout: 10000  
        master:
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource 
          unique-resource-name: master  
          xa-properties:
            user: root  
            password: 123456  
            url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8
        salve:
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          unique-resource-name: salve 
          xa-properties:
            user: root  
            password: root  
            url: jdbc:mysql://localhost:3307/boot?useUnicode=true&characterEncoding=utf-8
    enabled: true  
  datasource:
    druid:
      stat-view-servlet:
        login-password: admin
        login-username: admin

    